### PR TITLE
feat(#859): PartOps — segmentation preview + split into per-part submeshes (Slices A+B)

### PR DESCRIPTION
**Pull request by fernandotonon**
Epic **[#859 PartOps](https://github.com/fernandotonon/QtMeshEditor/issues/859)** — turning AI mesh segmentation into real authoring operations. Delivers the tested pure-data core, segmentation preview (Slice A #860), and the **split** feature end-to-end (Slice B #861) across GUI + CLI + MCP.

## User-facing value

Turn a single fused character mesh into **named per-part submeshes** — `head`, `torso`, `left_arm`, `right_arm`, `left_leg`, `right_leg` — boundary vertices duplicated so parts are independent, all attributes preserved, and (for skinned inputs) the **skeleton + bone weights kept** so the split character stays riggable.

- **GUI**: Object-mode Inspector → **"Split into Parts (AI)"** section (inspector-native controls). "AI assisted" toggle (ON by default = ONNX model; off = deterministic geometric/rig-prior fallback — both run locally). Undoable via Ctrl+Z.
- **CLI**: `qtmesh segment character.fbx --split-parts -o parts.fbx` (+ `--write-labels labels.json`, `--no-model`).
- **MCP**: `split_mesh_by_segments`.

## What's in this PR

- **`SubMeshOps`** — Ogre-buffer-free, unit-tested core (split/join/explode/peg math on `EditableSubMesh` data; foundation for slices C/D too).
- **`PartOpsMesh`** — Ogre adapter: reads an entity, runs the split, builds a fresh mesh, rebinds the skeleton + recompiles bone assignments, names each submesh (round-trips through FBX → reimport → Scene tree).
- **`SplitMeshCommand`** — undoable mesh-swap (a submesh-count change can't go through the in-place edit path; recreates the entity on the node, clears selection refs first to avoid dangling-pointer crashes, restores the original mesh on undo).
- **`PartOpsController`** — QML singleton driving the GUI button.
- **Slice A** — segmentation-preview caching in `EditModeController` (`partGroups()`, select/hide/exclude/rename; cleared on edit-mode exit + topology change).

## Testing
- `SubMeshOps_test` (14): grouping, split incl. attribute/bone preservation + boundary dup + per-material split + exclude + mismatch reject, join transform-bake + material separation, explode, boundary-plane accept/reject, peg gen/skip.
- `SplitMeshCommand_test` (4): ctor/accessor/error/undo-before-redo branches.
- `CLIPipeline_cmdsplitparts_coverage_test` (3): rigged FBX round-trip asserting multi-submesh + preserved triangle count + preserved skeleton + **named submeshes** + **unit-length normals** (dark-model guard).

All headless-safe; verified live on Rumba Dancing.fbx (multi-material → 12 parts) and Hip Hop Dancing.fbx (single-material → 6 clean parts).

## Limitations
Body-centric part labels; glTF coalesces same-material parts (FBX preserves them); for a multi-material part you get one submesh per source material (`head`, `head.1`, …).

## Remaining epic slices (follow-up PRs, on the tested core)
C explode/join scene nodes · D print-peg dialog · E remaining MCP tools (explode/join/print) · F docs polish.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

## Summary by CodeRabbit

* **New Features**
  * Added AI-assisted splitting of selected meshes into named, independently editable parts.
  * Added segmentation preview groups with face selection and per-part visibility, exclusion, and display-name controls.
  * Added CLI options to export segmentation labels or split parts into an output mesh.
  * Added MCP support for splitting meshes by detected segments.
  * Preserved submesh names, materials, normals, skeletons, and bone assignments during export.

* **Tests**
  * Added coverage for splitting, label exports, mesh attributes, naming, and undo behavior.

* **Documentation**
  * Documented CLI usage and PartOps workflows.

### CODE REVIEW

**Comment by fernandotonon** [comment]
Addressed all three findings in f6385abf:

**@codex (P2 — normals recomputed):** Fixed. `createNewMesh` gained a `recomputeNormals` flag (default true; all existing callers unchanged), and `PartOpsMesh::buildMesh` now passes `false` so the source normals `SubMeshOps` copied (incl. authored / hard-edge) upload verbatim instead of being recomputed.

**@codex (P2 — labels spanning materials):** Fixed. `splitByFaceGroups` now keys builders by **(label, source material)**, so a part whose triangles come from multiple source materials emits one submesh per material (named `torso`, `torso.1`, …) instead of collapsing onto the first triangle's material. `assignPartMaterials` still intentionally collapses to one generated material. Two new unit tests cover both branches, and the rigged round-trip test now exercises the real 11-material Rumba mesh.

**@coderabbitai (Major — stale in-flight segmentation):** Fixed. `clearSegmentationCache` (run on any topology change / edit-mode exit) now fires the existing `m_segmentCancel` atomic. The worker's completion handler already no-ops when that flag is set, so a job that finishes after a topology edit reports 'cancelled' rather than mapping stale labels onto the reshuffled triangle stream. Reused the proven cancellation path rather than adding a parallel generation counter.

All 17 PartOps tests green locally (14 core + 3 CLI).

**Comment by fernandotonon** [comment]
Addressed the review + fixed the CI link failure in 984bf762:

**CI (`unit-tests-linux` build-wrapper link error):** `PartOpsController.cpp` was only in `src/CMakeLists.txt`, so `mainwindow.cpp` (compiled into the test-common lib) had an undefined reference to `PartOpsController::qmlInstance` in the per-file test executables. Added it to `tests/CMakeLists.txt` (verified the symbol is now defined in `libqtmesh_test_common.a`).

**@coderabbitai Critical — use-after-free in `split_mesh_by_segments`:** fixed. Captured `entity->getName()` into a local *before* `push()` (which destroys the entity via the mesh swap), and return the cached name.

**@coderabbitai Major — `M_PI` portability:** fixed. `float(M_PI)` → `Ogre::Math::PI` (no `_USE_MATH_DEFINES` MSVC break).

**@coderabbitai Major — duplicate submesh names on import:** fixed. `MeshProcessor` now disambiguates a repeated `aiMesh::mName` with an `_N` suffix before `nameSubMesh`, so two same-named source meshes no longer resolve to one submesh. The round-trip test asserts all names are unique.

**@coderabbitai Major — part-group `ui.action` breadcrumbs:** added for select / hide / show / exclude / include / rename (logging only the part id, never the user-provided display name).

**@coderabbitai Minor — GUI split `ui.action` breadcrumb:** added in `PartOpsController::splitSelectedIntoParts`.

**@coderabbitai Minor — `selectPartGroup` doc:** clarified it returns the polygon count (n-gons count once), not faces.

**Already fixed in earlier commits (stale findings):** @codex P2 normals-recompute (→ `createNewMesh(recomputeNormals=false)`), @codex P2 per-material split (→ builders keyed by (label, source material)), @coderabbitai in-flight segmentation cancel (→ `clearSegmentationCache` fires `m_segmentCancel`).

21 PartOps tests green locally.
